[platformio]
default_envs = spotpear_s3_touch_lcd_28d
src_dir = firmware
include_dir = firmware/include

[env:spotpear_s3_touch_lcd_28d]
platform = espressif32@6.9.0
board = spotpear_s3_touch_lcd_28d
framework = arduino
board_build.flash_size = 8MB
board_build.partitions = partitions/ota_8mb.csv
board_build.filesystem = littlefs
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_upload.flash_size = 8MB
monitor_speed = 115200
upload_speed = 115200
upload_port = COM15
build_flags =
  -D MICRO_RADAR_VERSION=\"0.1.0-dev\"
  -D BOARD_SPOTPEAR_S3_TOUCH_LCD_28D=1
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D ARDUINO_LOOP_STACK_SIZE=8192
lib_deps =
  bblanchon/ArduinoJson@7.2.1
  mathieucarbou/ESP Async WebServer@3.0.6
  mathieucarbou/AsyncTCP@3.3.2
build_src_filter =
  +<main.cpp>
  +<src/>
  -<display_smoke_main.cpp>
check_tool = cppcheck
check_flags =
  cppcheck: --enable=warning,style,performance,portability --inline-suppr

[env:display_smoke]
platform = espressif32@6.9.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.flash_size = 8MB
board_upload.flash_size = 8MB
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
upload_speed = 115200
upload_port = COM15
monitor_speed = 115200
build_flags =
  -D MICRO_RADAR_VERSION=\"0.1.0-dev\"
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
build_src_filter =
  -<*>
  +<display_smoke_main.cpp>
